name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
