name: "Get & Cache dependencies (composite action)"
description: "Get and cache npm dependencies"
inputs:
  caching:
    description: "Option for caching dependencies"
    required: false
    default: true
outputs:
  used-cache:
    description: "Whether the cache was used or not."
    value: ${{ steps.install.outputs.cache }}
runs:
  using: "composite"
  steps:
  - name: Cache dependencies
    if: ${{ inputs.caching == 'true' }}
    id: cache
    uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != "true"
    run: |
      npm ci
      echo: "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
    shell: bash
