name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main # main
      - "dev-*" # dev-1 dev-new dev-blah-blah
      - "feat/**" # feat/new feat/new/form feat/new-blah/form/button
    paths-ignore:
      - "./github/workflows/*"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
